reservas/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = "reservas"

admin.site.site_header = "Administración de Reservas"
admin.site.site_title = "Reservas del restaurant"
admin.site.index_title = "Sitio de administración de Reservas"

urlpatterns = [
    path("", views.index, name="index"),
    path("seleccion/", views.seleccion, name="seleccion"),
    path("reservar/", views.reservar_mesa, name="reservar_mesa"),
    path("modificar/", views.modificar, name="modificar"),
    path("baja/", views.baja, name="baja"),
    path("modificar_reserva/", views.modificar_reserva, name="modificar_reserva"),
    path("modificar_descripcion", views.modificar_descripcion, name="modificar_descripcion"),
    path("baja_reserva/", views.baja_reserva, name="baja_reserva"),
    
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from reservas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservas/', include("reservas.urls")),
    path('accounts/logout/', views.cerrar_sesion, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

reservas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Obtiene el ultimo id de un usuario registrado. Sirve para linkear de usuario a cliente (Todo usuario que se loguea es un cliente)
def get_last_user_id():
    last_user = User.objects.last()
    if last_user:
        return last_user.id
    else:
        return 1  #al else no entra 

class Cliente(models.Model):
    usuario = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        default=1  # Utiliza el método como valor predeterminado
    )
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    correo = models.EmailField()

    def __str__(self):
        return f"{self.apellido} {self.nombre}"

class Mesa(models.Model):
    ocupado = models.BooleanField(default=False)
    descripcion = models.TextField(null=True)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f"Mesa: {self.id}"

reservas/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Mesa, Cliente
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.shortcuts import redirect

# Create your views here.
@login_required
def index(request):
    return render(request, "reservas/index.html")

def cerrar_sesion(request):
    logout(request)
    return index(request)

@login_required
def seleccion(request):
    disponibles = mesas_disponibles()
    return render(request, "reservas/seleccion.html", {
        "mesas": disponibles,
    })

@login_required
def reservar_mesa(request):
    if request.method == "POST":
        id_mesa = int(request.POST.get("mesa"))
        #agregar mesa a cliente y cambiar estado de mesa a Ocupado
        try:
            mesa = Mesa.objects.get(id=id_mesa)
            mesa.ocupado = True
            mesa.descripcion = str(request.POST.get("descripcion"))
            mesa.cliente = request.user.cliente
            mesa.save()
            return render(request, "reservas/index.html", {'success_message': 'Reserva realizada con éxito.'})
        except Mesa.DoesNotExist:
            return HttpResponseRedirect(reverse("index"))
        
#Cambia la descripción de la mesa.
@login_required
def modificar(request):
    mesascliente = mesas_cliente(request.user.cliente.id)
    return render(request, "reservas/modificar.html", {
        "mesas": mesascliente 
    })

@login_required
def baja(request):
    mesascliente = mesas_cliente(request.user.cliente.id)
    return render(request, "reservas/baja.html", {
        "mesas": mesascliente
    })

@login_required
def baja_reserva(request):
    if request.method == "POST":
        mesa_id = request.POST.get('mesa_id')
        mesa = Mesa.objects.get(id=mesa_id)
        mesa.descripcion = ""
        mesa.cliente = None
        mesa.ocupado = False
        mesa.save()
        return render(request, "reservas/index.html", {'success_message': 'Reserva dada de baja con éxito.'})  #Falta hacer comentarios de exito, o alert

#devuelve todas las mesas que contienen al cliente
def mesas_cliente(id_cliente):
    cliente = Cliente.objects.get(id=id_cliente)
    mesas = Mesa.objects.all()
    mesas_del_cliente = []
    for mesa in mesas:
        if mesa.cliente == cliente:
            mesas_del_cliente.append(mesa)
    return mesas_del_cliente

#devuelve todas las mesas libres
def mesas_disponibles():
    mesas = Mesa.objects.all()
    disponibles = []
    for mesa in mesas:
        if not mesa.ocupado:
            disponibles.append(mesa)
    return disponibles

@login_required
def modificar_reserva(request):#esta mal todavia
    if request.method == "POST":
        mesa_id = request.POST.get('mesa_id')
        mesa = Mesa.objects.get(id=mesa_id)
        return render(request, "reservas/modificar_reserva.html", {
        "mesa": mesa
    })
    
@login_required
def modificar_descripcion(request):
    if request.method == "POST":
        mesa_id = request.POST.get('mesa_id')
        descripcion = request.POST.get('text')
        mesa = Mesa.objects.get(id=mesa_id)
        mesa.descripcion = descripcion
        mesa.save()
        return render(request, "reservas/index.html", {'success_message': 'Reserva modificada con éxito.'}) 
    

reservas/templates/reservas/baja.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}
    {% if mesas %}
    <h1>Dar de baja reservas</h1>
    
    <form method="post" action="{% url 'reservas:baja_reserva' %}">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Número de mesa</th>
                    <th>Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for mesa in mesas %}
                <tr>
                    <td>{{ mesa.id }}</td>
                    <td>{{ mesa.descripcion }}</td>
                    <td><button type="submit" name="mesa_id" value="{{mesa.id}}" class="btn btn-danger">Dar de baja reserva</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        
    </form>
    {% else %}
        No se registraron reservas.
    {% endif%}
{% endblock %}

reservas/templates/reservas/disponibles.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}
<h1>Hola, {{ request.user.cliente.nombre }} disponibles</h1>
{% endblock %}

reservas/templates/reservas/index.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}
    <script>
        // Verificar si hay un mensaje de éxito en el contexto de la plantilla
        var successMessage = "{{ success_message }}";
        if (successMessage) {
            alert(successMessage);
        }
    </script>
    <h1>Hola, {{ request.user.cliente.nombre }}</h1>
{% endblock %}

reservas/templates/reservas/modificar.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}
    {% if mesas %}
    <h1>Modificar reservas</h1>
    
    <form method="post" action="{% url 'reservas:modificar_reserva' %}">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Número de mesa</th>
                    <th>Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for mesa in mesas %}
                <tr>
                    <td>{{ mesa.id }}</td>
                    <td>{{ mesa.descripcion }}</td>
                    <input type="hidden" name="mesa_id" value="{{ mesa.id }}">
                    <td><button class="btn btn-success" type="submit">Modificar reserva</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        
    </form>
    {% else %}
        No se registraron reservas.
    {% endif%}
{% endblock %}

reservas/templates/reservas/modificar_reserva.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}
    <h1>Modificar reserva</h1>
    
    <form method="post" action="{% url 'reservas:modificar_descripcion' %}">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Número de mesa</th>
                    <th>Descripción</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ mesa.id }}</td>
                    <td><input name="text" type="text" placeholder="{{ mesa.descripcion }}"/></td>
                    <input type="hidden" name="mesa_id" value="{{ mesa.id }}">
                    <td><button class="btn btn-success" type="submit" >Modificar reserva</button></td>
                </tr>
            </tbody>
        </table>
        
    </form>
    
{% endblock %}

reservas/templates/reservas/navbar.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Reservas</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 
        <nav class="navbar navbar-expand-lg bg-body-tertiary" >
            <div class="container-fluid">
              <h1 class="navbar-brand" href="#">Reservas</h1>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link active" aria-current="page" href="{% url 'reservas:index' %}">Inicio</a>
                  <a class="nav-link active" href="{% url 'reservas:seleccion' %}">Seleccionar mesas</a>
                  <a class="nav-link active" href="{% url 'reservas:modificar' %}">Modificar reservas</a>
                  <a class="nav-link active" href="{% url 'reservas:baja' %}">Dar de baja reservas</a>
                  <a class="nav-link active" style="color:red" href="{% url 'logout' %}">Cerrar sesión</a>

                </div>
              </div>
            </div>
          </nav>
          <div class="card">
            <div class="card-body">
          
              {% block cuerpo %}
              {% endblock %}
            </div>
          </div>
    </body>
</html>

reservas/templates/reservas/seleccion.html
{% extends "reservas/navbar.html" %}

{% block cuerpo %}

<h1>Seleccionar Mesa</h1>

{% if mesas %}
<form method="post" action="{% url 'reservas:reservar_mesa' %}">
    {% csrf_token %}
    Número de mesa: 
    <select name="mesa">
        {% for mesa in mesas %}
            <option value="{{ mesa.id }}">{{ mesa.id }}</option>
        {% endfor %}
    </select>
    <br/>
    <br/>
    Descripción: 
    <input type="text" name="descripcion"/>
    <br/>
    <br/>
    <button class="btn btn-success" type="submit">Enviar</button>
</form>
{% else %}
    No hay mesas disponibles.
{% endif%}


{% endblock %}